name: Repository-Variables-Secrets

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Example: Access a repository variable (if you have one)
      - name: Access Repo Variable
        run: echo ${{vars.USERNAME}}

      # Access API_KEY secret
      - name: Access API_KEY Secret
        run: echo {{ secrets.API_KEY }}

      # Access password secret
      - name: Access Password Secret
        run: echo ${{ secrets.PASSWORD }}
